arb-dir: lib/l10n
template-arb-file: app_cs.arb
output-dir: lib/localization
output-localization-file: app_localizations.dart
untranslated-messages-file: untranslated_messages.json
synthetic-package: false

